### ISSUE TITLE
AcoustID API key

### ISSUE THREAD

**Issue by lalinsky** [albertz/music-player#51]
It seems that you are using the AcoustID API key from pyacoustid. Please register your own one.

https://github.com/albertz/music-player/blob/aba56e483a4a98779ed0cb24fe171189aeb0423b/SongEdit.py#L118

**Comment by lalinsky** [comment]
Also here https://github.com/albertz/music-player-core/blob/master/examples/test_acoustid.py#L55

**Comment by albertz** [comment]
Whoops, sorry about that, I forgot to create my own. Fixed in cfe4c74 and 141bced7.

**Comment by lalinsky** [comment]
Thanks.
